### ISSUE TITLE
thresholder should use the parallel spikespace

### ISSUE THREAD

**Issue by moritzaugustin** [brian-team/brian2cuda#9] opened 2015-10-29 15:54 UTC
the parallel spikespace which is used in the synaptic propagation/effect application & spike monitor is so-far not yet used
currently: mainly the first block (`atomicAdd` on global memory) fills the spike space -- almost purely sequentially
should be: all blocks in parallel should fill their respective portion of the spike space using only shared memory `atomicAdd` (for index computation and local spike count in smem) and only at the very end an `atomicAdd` on the global memory to find the total no of spikes (global spike count) as the sum of the local spike counts

**Comment by moritzaugustin** [comment] 2015-10-29 16:36
I think @Kwartke you had implemented this already, i.e., it might be worth to scan the old branches

**Comment by denisalevi** [comment] 2016-06-03 11:32
It turns out, that using `atomicAdd` on shared memory instead of global memory in the thresholder kernel is slower (on GTX Titan Black). A performance plot comparing the two implementations for N=10000 neurons, with every n-th neuron spiking in each time step can be found ![here](https://github.com/brian-team/brian2cuda/blob/master/dev/issues/issue9_spikespace/performance_atomics.png).
The time measurements were done using the `nvprof` command line profiler and are average values of 10 kernel calls.

Time measurement of only the `atomicAdd` instructions within the kernel for the two implementations using `clock()` in the kernel code (for the case of all neurons spiking) show the same results:
- using shared atomics takes `~35.5 us` per kernel call 
- using global atomics takes `~9.6 us` per kernel call

The code for the time measurements and how to reproduce them can be found in the [dev/issues/issue9_spikespace](https://github.com/brian-team/brian2cuda/tree/master/dev/issues/issue9_spikespace) folder (commit dee9bf7). 
`clock()` measures the number of clocks per-multiprocessor counter, so this is the time the device takes executing the thread (including waiting/replays of conflicting atomics) ([as explained here](http://docs.nvidia.com/cuda/cuda-c-programming-guide/#time-function)).

In [this nvidia blogpost](https://devblogs.nvidia.com/parallelforall/gpu-pro-tip-fast-histograms-using-shared-atomics-maxwell/) a good explanation can be found, where shared and global atomics are compared for a similar use case.
> Kepler emulates shared memory atomics in software [...]. 


> However the Maxwell architecture features hardware support for shared memory atomics and we can clearly see that in all cases the shared atomics version performs best.

This explains the results for our performance measurements (The GTX Titan Black is a Kepler-GPU). The performance gain with shared atomics on Maxwell architectures in aboves blog post is also only a factor of 2 (independent of the number of conflicting atomics).

Therefore, we keep the implementation using global atomics. Optional shared atomics for Maxwell architectures could be considered at a later development stage.
The implementation using shared atomics can be found in the `issue9_spikespace` branch (eb215d4).

Closing the issue.

**Closed by denisalevi** 2016-06-03 11:32 UTC
Labels: high priority, in progress
